### ISSUE TITLE
例程recognize编译失败

### ISSUE THREAD

**Issue by 2502797718** [espressif/esp-moonlight#2]
提示是缺失一堆数学函数sin,log之类。

**Comment by alic-maker** [comment]
If you can provide debug logs in the monitor, it will help solve the problem. 
There are two tips:
 - Check your ESP-IDF version is [release/v4.0](https://github.com/espressif/esp-idf/tree/release/v4.0). 
 - In addition, you can try to use the latest commit

**Comment by 2502797718** [comment]
> If you can provide debug logs in the monitor, it will help solve the problem.
> There are two tips:
> 
> * Check your ESP-IDF version is [release/v4.0](https://github.com/espressif/esp-idf/tree/release/v4.0).
> * In addition, you can try to use the latest `commit`
[编译时错误信息.txt](https://github.com/espressif/esp-moonlight/files/4665932/default.txt)
这是编译信息，用的是v4.0

**Comment by 2502797718** [comment]
最新版本的源码可以编译通过

**Comment by alic-maker** [comment]
This error may be due to  some problems in CMakeLists.txt. The latest code is recommended

**Comment by alic-maker** [comment]
@2502797718 If your question is resolved, please close the issue. Thanks!
