### ISSUE TITLE
speech_recognition 无法进行正常识别

### ISSUE THREAD

**Issue by hljswl** [espressif/esp-moonlight#3]
1. 开发环境
模组或开发板：esp-moonlight开发板
ESP-IDF 版本：cd4fa46f5 / ESP-IDF v4.2-dev-1303-gcd4fa46f5-dirty
2. 问题描述
编译最新例程里面的 7_recognition 后不能进行语音识别。关键字唤醒没有反应。

**Comment by alic-maker** [comment]
Now, the esp-moonlight is based on ESP-IDF release/v4.0. Please see https://github.com/espressif/esp-moonlight/blob/master/docs/zh_CN/gettingstarted.rst#%E8%8E%B7%E5%8F%96-esp-moonlight
